# Generated by Django 5.1.3 on 2025-04-21 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("disease_cases", "0001_initial"),
        ("health", "0001_initial"),
        ("importer", "0004_alter_importfile_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="DiseaseCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("federative_unit", models.CharField(max_length=100)),
                ("month_year", models.DateField()),
                ("value", models.CharField(max_length=100)),
                (
                    "cid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="health.cid"
                    ),
                ),
                (
                    "file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="importer.importfile",
                    ),
                ),
                (
                    "type_health",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="health.typecontent",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Symptoms",
        ),
    ]
