# Generated by Django 5.1.3 on 2025-04-22 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("disease_cases", "0002_diseasecase_delete_symptoms"),
    ]

    operations = [
        migrations.RenameField(
            model_name="diseasecase",
            old_name="federative_unit",
            new_name="federative_unit_name",
        ),
    ]
