# Generated by Django 4.2.20 on 2025-07-12 18:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disease_cases', '0003_rename_federative_unit_diseasecase_federative_unit_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diseasecase',
            name='month_year',
        ),
        migrations.AddField(
            model_name='diseasecase',
            name='register_at',
            field=models.DateField(default=datetime.date(2020, 1, 1)),
            preserve_default=False,
        ),
    ]
