# Generated by Django 4.2.20 on 2026-06-24 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0006_alter_importfile_type'),
        ('disease_cases', '0004_remove_diseasecase_month_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diseasecase',
            name='register_at',
            field=models.DateTimeField(),
        ),
        migrations.CreateModel(
            name='SivepSrag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nu_notific', models.BigIntegerField(unique=True)),
                ('dt_interna', models.DateField(blank=True, null=True)),
                ('sg_uf', models.CharField(max_length=2)),
                ('co_mun_res', models.IntegerField(blank=True, null=True)),
                ('classi_fin', models.SmallIntegerField(blank=True, null=True)),
                ('evolucao', models.SmallIntegerField(blank=True, null=True)),
                ('cs_sexo', models.CharField(blank=True, max_length=1, null=True)),
                ('nu_idade_n', models.IntegerField(blank=True, null=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='importer.importfile')),
            ],
        ),
    ]
