# Generated by Django 4.2.20 on 2026-06-24 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disease_cases', '0005_alter_diseasecase_register_at_sivepsrag'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='sivepsrag',
            table='sivep_srag',
        ),
    ]
