# Generated by Django 5.1.3 on 2025-04-21 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("geo_data", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Burned",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("register_at", models.DateTimeField()),
                ("no_rain_days", models.IntegerField()),
                ("precipitation", models.FloatField()),
                ("fire_risk", models.FloatField()),
                ("latitude", models.CharField(max_length=15)),
                ("longitude", models.CharField(max_length=15)),
                ("frp", models.FloatField()),
                (
                    "biome",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="geo_data.biome"
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="geo_data.city"
                    ),
                ),
                (
                    "federative_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="geo_data.federativeunit",
                    ),
                ),
                (
                    "satellite",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="geo_data.satellite",
                    ),
                ),
            ],
        ),
    ]
