# Generated by Django 5.1.3 on 2025-02-04 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burned', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='burned',
            name='latitude',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='burned',
            name='longitude',
            field=models.CharField(max_length=15),
        ),
    ]
