# Generated by Django 4.2.20 on 2025-07-08 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("importer", "0004_alter_importfile_status"),
        ("burned", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="burned",
            name="file",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="importer.importfile",
            ),
        ),
    ]
