# Generated by Django 4.2.20 on 2025-07-08 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("importer", "0005_alter_importfile_type"),
        ("burned", "0002_burned_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="burned",
            name="file",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="importer.importfile"
            ),
        ),
    ]
