# Generated by Django 5.1.3 on 2024-11-26 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('health', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Symptoms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('federative_unit', models.CharField(max_length=100)),
                ('month_year', models.DateField()),
                ('value', models.CharField(max_length=100)),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.cid')),
                ('type_health', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.typecontent')),
            ],
        ),
    ]
