# Generated by Django 5.1.3 on 2024-12-11 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0003_importfile_end_at_importfile_start_at_and_more'),
        ('symptoms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='symptoms',
            name='file',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='importer.importfile'),
            preserve_default=False,
        ),
    ]
