# Generated by Django 5.1.3 on 2024-12-23 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symptoms', '0002_symptoms_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symptoms',
            name='month_year',
            field=models.DateField(max_length=20),
        ),
    ]
