# Generated by Django 5.1.3 on 2025-01-08 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symptoms', '0003_alter_symptoms_month_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symptoms',
            name='month_year',
            field=models.DateField(),
        ),
    ]
