# Generated by Django 5.1.3 on 2025-01-21 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biome',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='city',
            name='state',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='satellite',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
