# Generated by Django 5.1.3 on 2025-02-03 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0004_alter_city_federative_unit_alter_city_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='federative_unit',
        ),
    ]
