# Generated by Django 5.1.3 on 2024-11-27 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImportFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('health', 'Saúde'), ('fire', 'Queimadas')], max_length=10, verbose_name='Tipo de Arquivo')),
                ('file', models.FileField(upload_to='imported_files/', verbose_name='Arquivo')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Enviado em')),
            ],
        ),
    ]
