# Generated by Django 5.1.3 on 2024-11-27 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importfile',
            name='file',
            field=models.FileField(upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='importfile',
            name='type',
            field=models.CharField(choices=[('health', 'Saúde'), ('fire', 'Queimadas')], max_length=10),
        ),
        migrations.AlterField(
            model_name='importfile',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
