# Generated by Django 5.1.3 on 2024-12-11 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0002_alter_importfile_file_alter_importfile_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='importfile',
            name='end_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='importfile',
            name='start_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='importfile',
            name='status',
            field=models.IntegerField(choices=[(1, 'Aberto'), (2, 'Iniciado'), (1, 'Finalizado')], default=1),
        ),
    ]
