# Generated by Django 5.1.3 on 2024-12-23 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0003_importfile_end_at_importfile_start_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importfile',
            name='status',
            field=models.IntegerField(choices=[(1, 'Aberto'), (2, 'Iniciado'), (3, 'Finalizado')], default=1),
        ),
    ]
