# Generated by Django 4.2.20 on 2025-07-08 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("importer", "0004_alter_importfile_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="importfile",
            name="type",
            field=models.CharField(
                choices=[("health", "Saúde"), ("burned", "Queimadas")], max_length=10
            ),
        ),
    ]
