# Generated by Django 4.2.20 on 2026-06-24 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0005_alter_importfile_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importfile',
            name='type',
            field=models.CharField(choices=[('health', 'Saúde'), ('burned', 'Queimadas'), ('sivep_srag', 'SIVEP SRAG')], max_length=10),
        ),
    ]
